# Generated by Django 2.0.4 on 2018-05-03 10:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180503_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('home_address', models.CharField(blank=True, max_length=300)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=50)),
                ('dog_breed', models.IntegerField(choices=[(1, 'Affenpinscher'), (2, 'Afghan Hound'), (3, 'Airedale Terrier'), (4, 'Akita'), (5, 'Alaskan Malamute'), (6, 'American Cocker Spaniel'), (7, 'American Eskimo Dog (Miniature)'), (8, 'etc')])),
                ('dog_birth', models.DateField(blank=True, null=True)),
                ('dog_description', models.CharField(blank=True, max_length=300)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Client')),
            ],
        ),
    ]
