# Generated by Django 2.0.4 on 2018-05-05 10:05

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20180505_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.DateTimeField()),
                ('service_option', models.IntegerField(choices=[(1, 'wash only'), (2, 'wash and nail clipping'), (3, 'deluxe grooming'), (4, 'etc')])),
                ('appointment_comment', models.CharField(blank=True, max_length=300)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_of_appointment', to='accounts.Client')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_appointed_for_user', to='accounts.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Groomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groomer_name', models.CharField(max_length=50)),
                ('groomer_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TimeBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_time', models.DateTimeField()),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_of_groomer', to='appointment.Groomer')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='groomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groomer_of_appointment', to='appointment.Groomer'),
        ),
    ]
