# Generated by Django 2.0.4 on 2018-05-10 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20180505_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_appoint', to='accounts.Dog'),
        ),
    ]
