# Generated by Django 2.0.4 on 2018-05-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20180510_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='groomer',
        ),
        migrations.RemoveField(
            model_name='timebooked',
            name='groomer',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Groomer',
        ),
        migrations.DeleteModel(
            name='TimeBooked',
        ),
    ]
